src/Entity/Ingredient.php
<?php

namespace App\Entity;

use App\Repository\IngredientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="ingredients")
 * @ORM\Entity(repositoryClass=IngredientRepository::class)
 */
class Ingredient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ingredient_name;

    /**
     * @ORM\Column(type="float")
     */
    private $ingredient_price;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vegetarian;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vegan;

    /**
     * @ORM\ManyToMany(targetEntity=Pizza::class, mappedBy="pizza_ingredients")
     */
    private $pizzas;

    public function __construct()
    {
        $this->pizzas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIngredientName(): ?string
    {
        return $this->ingredient_name;
    }

    public function setIngredientName(string $ingredient_name): self
    {
        $this->ingredient_name = $ingredient_name;

        return $this;
    }

    public function getIngredientPrice(): ?float
    {
        return $this->ingredient_price;
    }

    public function setIngredientPrice(float $ingredient_price): self
    {
        $this->ingredient_price = $ingredient_price;

        return $this;
    }

    public function getVegetarian(): ?bool
    {
        return $this->vegetarian;
    }

    public function setVegetarian(?bool $vegetarian): self
    {
        $this->vegetarian = $vegetarian;

        return $this;
    }

    public function getVegan(): ?bool
    {
        return $this->vegan;
    }

    public function setVegan(?bool $vegan): self
    {
        $this->vegan = $vegan;

        return $this;
    }

    /**
     * @return Collection|Pizza[]
     */
    public function getPizzas(): Collection
    {
        return $this->pizzas;
    }

    public function addPizza(Pizza $pizza): self
    {
        if (!$this->pizzas->contains($pizza)) {
            $this->pizzas[] = $pizza;
            $pizza->addPizzaIngredient($this);
        }

        return $this;
    }

    public function removePizza(Pizza $pizza): self
    {
        if ($this->pizzas->removeElement($pizza)) {
            $pizza->removePizzaIngredient($this);
        }

        return $this;
    }

}

src/Entity/Pizza.php
<?php

namespace App\Entity;

use App\Repository\PizzaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="pizzas")
 * @ORM\Entity(repositoryClass=PizzaRepository::class)
 */
class Pizza
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $pizza_name;

    /**
     * @ORM\ManyToOne(targetEntity=Base::class, inversedBy="pizzas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $pizza_base;

    /**
     * @ORM\ManyToOne(targetEntity=Size::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $pizza_size;

    /**
     * @ORM\ManyToMany(targetEntity=Ingredient::class, inversedBy="pizzas")
     */
    private $pizza_ingredients;

    public function __construct()
    {
        $this->pizza_ingredients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPizzaName(): ?string
    {
        return $this->pizza_name;
    }

    public function setPizzaName(string $pizza_name): self
    {
        $this->pizza_name = $pizza_name;

        return $this;
    }

    public function getPizzaBase(): ?Base
    {
        return $this->pizza_base;
    }

    public function setPizzaBase(?Base $pizza_base): self
    {
        $this->pizza_base = $pizza_base;

        return $this;
    }

    public function getPizzaSize(): ?Size
    {
        return $this->pizza_size;
    }

    public function setPizzaSize(?Size $pizza_size): self
    {
        $this->pizza_size = $pizza_size;

        return $this;
    }

    /**
     * @return Collection|Ingredient[]
     */
    public function getPizzaIngredients(): Collection
    {
        return $this->pizza_ingredients;
    }

    public function addPizzaIngredient(Ingredient $pizzaIngredient): self
    {
        if (!$this->pizza_ingredients->contains($pizzaIngredient)) {
            $this->pizza_ingredients[] = $pizzaIngredient;
        }

        return $this;
    }

    public function removePizzaIngredient(Ingredient $pizzaIngredient): self
    {
        $this->pizza_ingredients->removeElement($pizzaIngredient);

        return $this;
    }


    public function getPizzaPrice(): float
    {
        $total = 0;

        $total += $this->pizza_base->getBasePrice();
        $total += $this->pizza_size->getSizePrice();

        foreach ($this->pizza_ingredients as $ingredient){
            $total += $ingredient->getIngredientPrice();
        }

        return $total;
    }




    public function VeganOrVegetarian(): string
    {
        $isVegan = true;
        $isVegetarian = true;

        foreach ($this->pizza_ingredients as $ingredient){
            $vegan = $ingredient->getVegan();
            $vegetarian = $ingredient->getVegetarian();

            if ($vegan == false) {
                $isVegan = false;
            }
            if ($vegetarian == false) {
                $isVegetarian = false;
            }
        }

        if ($isVegan == true) {
            $result = "Végan";
        } else if ($isVegetarian == true) {
            $result = "Végétarienne";
        } else {
            $result = "";
        }

        return $result;
    }
}

src/Form/PizzaType.php
<?php

namespace App\Form;


use App\Entity\Base;
use App\Entity\Ingredient;
use App\Entity\Pizza;
use App\Entity\Size;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PizzaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pizza_name', TextType::class, [
                "label" => "Nom de la pizza",
                "attr" => ["class" => "mb-4"]
            ])
            ->add('pizza_base', EntityType::class, [
                "label" => "Choisir une base",
                "attr" => ["class" => "mb-4"],
                "class" => Base::class,
                "choice_label" => function ($base) {
                    return $base->getBaseName() . " (" . $base->getBasePrice() . " €)";
                }
            ])
            ->add('pizza_size', EntityType::class, [
                "label" => "Choisir la taille de la pizza",
                "attr" => ["class" => "mb-4"],
                "class" => Size::class,
                "choice_label" => function ($size) {
                    return $size->getSizeName() . " (" . $size->getSizePrice() . " €)";
                }
            ])
            ->add('pizza_ingredients', EntityType::class, [
                "label" => "Liste d'ingrédient :",
                "class" => Ingredient::class,
                "choice_label" => function ($ingredient) {
                    return $ingredient->getIngredientName() . " (" . $ingredient->getIngredientPrice() . " €)";
                },
                "expanded" => true,
                "multiple" => true
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pizza::class,
        ]);
    }



}

src/Controller/PizzaController.php
<?php

namespace App\Controller;

use App\Entity\Pizza;
use App\Form\PizzaType;
use App\Repository\PizzaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/pizza")
 */
class PizzaController extends AbstractController
{
    /**
     * @Route("/", name="pizza_index", methods={"GET"})
     */
    public function index(PizzaRepository $pizzaRepository): Response
    {
        return $this->render('pizza/index.html.twig', [
            'pizzas' => $pizzaRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="pizza_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $pizza = new Pizza();
        $form = $this->createForm(PizzaType::class, $pizza);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pizza);
            $entityManager->flush();

            return $this->redirectToRoute('pizza_index');
        }

        return $this->render('pizza/new.html.twig', [
            'pizza' => $pizza,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pizza_show", methods={"GET"})
     */
    public function show(Pizza $pizza): Response
    {
        return $this->render('pizza/show.html.twig', [
            'pizza' => $pizza,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="pizza_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Pizza $pizza): Response
    {
        $form = $this->createForm(PizzaType::class, $pizza);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pizza_index');
        }

        return $this->render('pizza/edit.html.twig', [
            'pizza' => $pizza,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pizza_delete", methods={"POST"})
     */
    public function delete(Request $request, Pizza $pizza): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pizza->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($pizza);
            $entityManager->flush();
        }

        return $this->redirectToRoute('pizza_index');
    }
}

templates/pizza/_delete_form.html.twig
<form method="post" action="{{ path('pizza_delete', {'id': pizza.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pizza.id) }}">
    <button class="btn btn-danger btn-block">Supprimer</button>
</form>

templates/pizza/_form.html.twig
{{ form_start(form) }}
<br>
    {{ form_widget(form) }}
    <br>

    <div class="flex">
        <div><button class="btn btn-primary btn-block">{{ button_label|default('ENREGISTRER') }}</button></div>

{{ form_end(form) }}

templates/pizza/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Pizza{% endblock %}

{% block body %}
    <h1>Modifier Pizza</h1>



        {{ include('pizza/_form.html.twig', {'button_label': 'Modifier'}) }}

        <!--<a href="{{ path('pizza_index') }}">back to list</a>-->

        {{ include('pizza/_delete_form.html.twig') }}
    </div>

{% endblock %}

templates/pizza/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pizza index{% endblock %}

{% block body %}
    <h1>Liste des pizzas</h1>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Taille</th>
                <th>Base</th>
                <th>Tarif</th>
                <th>Végan/Végétarien</th>
                <th>Actions</th>
            </tr>
        </thead>

        <tbody>
        {% for pizza in pizzas %}
            <tr>
                <td>{{ pizza.id }}</td>
                <td>{{ pizza.pizzaName }}</td>
                <td>{{ pizza.pizzaSize.getSizeName() }}</td>
                <td>{{ pizza.pizzaBase.getBaseName() }}</td>
                <td>{{ pizza.pizzaPrice }} €</td>
                <td>{{ pizza.VeganOrVegetarian }}</td>
                <td class="flex">
                    <div><a href="{{ path('pizza_show', {'id': pizza.id}) }}" class="btn btn-success btn-block">Détails</a></div>
                    <div><a href="{{ path('pizza_edit', {'id': pizza.id}) }}" class="btn btn-warning btn-block">Modifier</a></div>
                    {{ include('pizza/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('pizza_new') }}" class="btn btn-primary btn-block">CREER UNE NOUVELLE PIZZA</a>

{% endblock %}

templates/pizza/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Pizza{% endblock %}

{% block body %}
    <h1>Créer une nouvelle Pizza</h1>

    {{ include('pizza/_form.html.twig') }}

    <!--<a href="{{ path('pizza_index') }}">Liste pizzas</a>-->
{% endblock %}

templates/pizza/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pizza{% endblock %}

{% block body %}
    <h1>Détails Pizza</h1>

    <br><br>

    <table class="table">
        <tbody>
            <tr>
                <th>Id :</th>
                <td class="col-md-6">{{ pizza.id }}</td>
            </tr>
            <tr>
                <th>Nom :</th>
                <td class="col-md-6">{{ pizza.pizzaName }}</td>
            </tr>
            <tr>
                <th>Tarif :</th>
                <td class="col-md-6">{{ pizza.pizzaPrice }} €</td>
            </tr>
            <tr>
                <th>Taille :</th>
                <td class="col-md-6">{{ pizza.pizzaSize.getSizeName() }}</td>
            </tr>
        </tbody>
    </table>

    <br><br>

    <table class="table">
        <tbody>
            <tr>
                <th>INGREDIENTS :</th>
            </tr>
            {% for ingredient in pizza.pizzaIngredients %}
                <tr>
                    <td class="col-md-6">
                        {{ ingredient.ingredientName }}
                    </td>
                    <td class="col-md-6">
                        {{ ingredient.ingredientPrice }} €
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!--<a href="{{ path('pizza_index') }}">Retour à la liste</a>-->


    <div class="flex">
        <div><a href="{{ path('pizza_edit', {'id': pizza.id}) }}" class="btn btn-warning btn-block">Modifier</a></div>

        {{ include('pizza/_delete_form.html.twig') }}
    </div>


{% endblock %}